<html>
    <head>
    </head>
    <body>
        <ul>
            <li>Come</li>
            <li>Home</li>
            <li>to</li>
            <li>Sam</li>
            <li>Gerrard</li>
        </ul>
    </body>
</html>